## Classificação

In [1]:
from sklearn import tree
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score

In [2]:
iris = load_iris()
X = iris.data
y = iris.target

In [3]:
clf = tree.DecisionTreeClassifier(criterion='entropy', min_samples_split=2, min_samples_leaf=2, max_depth=3)

In [4]:
irisTree = clf.fit(X, y)

In [5]:
irisTree.predict([[2., 2., 2., 2.]])

array([0])

In [6]:
allScores = cross_val_score(clf, X, y, cv=10).mean()

In [7]:
allScores

0.96

## Regressão

In [8]:
from sklearn import tree
from sklearn.datasets import load_boston
from sklearn.model_selection import cross_val_score

In [9]:
boston = load_boston()
X = boston.data
y = boston.target

c:\Users\guIlherme\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing datas

In [10]:
reg = tree.DecisionTreeRegressor()

In [11]:
bostonTree = reg.fit(X[:-50], y[:-50])

In [12]:
bostonTree.predict(X[-50:])

array([13.2, 15.1, 13. , 13. , 14.1, 15.6, 22.7, 22.7, 22.7, 20.8, 13.2,
       13.1, 11.9, 10.9, 14.1, 21.7, 19.9, 28.7, 15.1, 17.2, 14.1, 17.9,
       14.1, 22.6, 22.7, 22.8, 28.7, 15. , 22.2, 20.8, 17.5, 22.7, 15.7,
       15.7, 15.7, 17.1, 19.6, 18.2, 21.7, 19.5, 19.5, 18.2, 19.8, 19.4,
       19.8, 26.6, 22.1, 23.6, 28.2, 22.1])

In [13]:
bostonTree.score(X[-50:],y[-50:])

0.12198018332281901

In [14]:
allScores = cross_val_score(reg, X, y, cv=10)
allScores

array([ 0.50855557,  0.52610395, -1.36982821,  0.06210661,  0.76623917,
        0.38763948, -0.12998397,  0.3542801 , -2.09610159, -0.99485763])

In [15]:
allScores.mean()

-0.19858465127796404